# Generated by Django 4.1.3 on 2022-11-29 10:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import petstagram_last.core.model_mixins
import petstagram_last.photos.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0002_create_pet'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', validators=[petstagram_last.photos.validators.validate_file_less_than_5mb])),
                ('description', models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(10, message='Минималната дължина на описанието е 10')])),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_publication', models.DateField(auto_now=True)),
                ('tagged_pets', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pets.pet')),
            ],
            bases=(petstagram_last.core.model_mixins.StrFromFieldsMixin, models.Model),
        ),
    ]
