# Generated by Django 4.1.3 on 2022-11-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_create_pet'),
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tagged_pets',
        ),
        migrations.AddField(
            model_name='photo',
            name='tagged_pets',
            field=models.ManyToManyField(blank=True, to='pets.pet'),
        ),
    ]
