# Generated by Django 4.1.3 on 2022-12-06 11:14

from django.db import migrations, models
import petstagram_last.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_remove_photo_tagged_pets_photo_tagged_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='photos', validators=[petstagram_last.photos.validators.validate_file_less_than_5mb]),
        ),
    ]
