# Generated by Django 4.1.3 on 2022-11-29 09:49

from django.db import migrations, models
import petstagram_last.core.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

    ]
