# Generated by Django 4.1.3 on 2022-11-29 09:52

from django.db import migrations, models
import petstagram_last.core.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('personal_photo', models.URLField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            bases=(petstagram_last.core.model_mixins.StrFromFieldsMixin, models.Model),
        ),
    ]
