# Generated by Django 4.1.3 on 2022-11-29 10:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import petstagram_last.core.model_mixins
import petstagram_last.photos.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0002_create_pet'),
    ]

    operations = [

    ]
